name: Style

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - run: sudo apt-get update && sudo apt-get install --yes clang-format
      - run: clang-format --dry-run --Werror src/policy.h src/plugin.cpp src/settings.cpp tests/policy_test.cpp
